### ISSUE TITLE
How to add Data2Semantics/powerlaws in the pom.xml?

### ISSUE THREAD

**Issue by swinghu** [Data2Semantics/powerlaws#1]
Hi ,there, I want user powerlaws to caculate the network metric, I found that when I add it in the pom.xml file it went wrong 

```
 <dependency>
        <groupId>data2semantics</groupId>
        <artifactId>powerlaws</artifactId>
        <version>0.0.1-SNAPSHOT</version>
 </dependency> 
```

have not published?

**Comment by pbloem** [comment]
Hi swinghu,

Sorry for the late response. You can now add the powerlaw lib through jitpack. I've added instructions to the readme.
